feat(Historail de Pagos): avanze maqueta visualizar paquete/recarga
wigilabs/miniapp_paquetesyrecargas pull request #2
Opened 2023-05-03 23:41 UTC by dMartinezHernandez

avance maqueta visualizar paquete/recarga

2023-05-04 11:03 UTC, jmejiaw approved these changes

2023-05-04 14:43 UTC, jhonnoriega1221 commented on pages/visualizarpaqueterecarga/index.acss
De momento no se pueden manejar width y height personalizados, dejarlo así como está con el TODO.

2023-05-04 14:44 UTC, jhonnoriega1221 submitted a review, later dismissed

2023-05-04 15:25 UTC, Joredjs requested changes

2023-05-04 15:25 UTC, Joredjs commented on pages/visualizarpaqueterecarga/index.acss
> +.widthimage {
@dMartinezHernandez agregar TODO

2023-05-04 15:25 UTC, Joredjs commented on pages/visualizarpaqueterecarga/index.axml
> +					<text class="c-heading-1 c-text-primary c-mt-20"> 3214238383 </text>
@dMartinezHernandez  Numero de línea quemada, quitarlo o agregar TODO

2023-05-04 15:25 UTC, Joredjs commented on pages/visualizarpaqueterecarga/index.js
> +		categorias: [
@dMartinezHernandez  categorias quemadas, quitarlo o agregar TODO

2023-05-04 15:25 UTC, Joredjs commented on pages/visualizarpaqueterecarga/index.js
> +		infoPaquete: {
@dMartinezHernandez paquete quemado, quitarlo o agregar TODO

2023-05-04 23:34 UTC, dMartinezHernandez commented
@Joredjs @jhonnoriega1221 @jmejiaw  ajuste realizados

2023-05-05 13:53 UTC, jhonnoriega1221 approved these changes

2023-05-05 16:21 UTC, merged